ALTER TABLE connections
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE zzz_connections
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE gi_connections
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
